- name: Deploy all analytics services to a single node
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: yes
    disable_edx_services: true
    insights_register_oauth_app: yes
    INSIGHTS_OAUTH2_APP_CLIENT_NAME: insights
    INSIGHTS_OAUTH2_APP_USERNAME: staff
    INSIGHTS_OAUTH2_APP_URL_ROOT: http://localhost:8110
    INSIGHTS_OAUTH2_URL_ROOT: http://127.0.0.1:8000/oauth2
    INSIGHTS_COURSE_API_URL: http://localhost:8000/api/course_structure/v0/
    INSIGHTS_SOCIAL_AUTH_REDIRECT_IS_HTTPS: 'false'
    INSIGHTS_SESSION_COOKIE_NAME: insights_sessionid
    INSIGHTS_CSRF_COOKIE_NAME: insights_csrftoken
    INSIGHTS_LANGUAGE_COOKIE_NAME: insights_language
  roles:
    - edxlocal
    - analytics_api
    - analytics_pipeline
    - insights
