- name: Deploy all analytics services to a single node
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: true
    insights_register_oauth_app: yes
  roles:
    - edxlocal
    - analytics_api
    - analytics_pipeline
    - insights
